//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ecommerce.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من نحن.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة للسلة.
        /// </summary>
        public static string AddToCart {
            get {
                return ResourceManager.GetString("AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة لقائمة الامنيات.
        /// </summary>
        public static string AddToWishlist {
            get {
                return ResourceManager.GetString("AddToWishlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جميع الاصناف.
        /// </summary>
        public static string AllCategories {
            get {
                return ResourceManager.GetString("AllCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجوائز.
        /// </summary>
        public static string AwardsWinned {
            get {
                return ResourceManager.GetString("AwardsWinned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السلة.
        /// </summary>
        public static string Cart {
            get {
                return ResourceManager.GetString("Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تواصل معنا.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اتصل بنا.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تواصل معنا على مدار 24 ساعة في اليوم.
        /// </summary>
        public static string Contactus24hoursaday {
            get {
                return ResourceManager.GetString("Contactus24hoursaday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العملة.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدماتنا.
        /// </summary>
        public static string CustomerService {
            get {
                return ResourceManager.GetString("CustomerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرجاع خلال 90 يومًا.
        /// </summary>
        public static string DaysReturn {
            get {
                return ResourceManager.GetString("DaysReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  صفقة اليوم .
        /// </summary>
        public static string DealOfTheDay {
            get {
                return ResourceManager.GetString("DealOfTheDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأقسام الرئيسية.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإيميل.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث DawElBeat.
        /// </summary>
        public static string EnterTextsearch {
            get {
                return ResourceManager.GetString("EnterTextsearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل عنوان بريدك الإلكتروني.
        /// </summary>
        public static string Enteryouremail {
            get {
                return ResourceManager.GetString("Enteryouremail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أخرى.
        /// </summary>
        public static string Extras {
            get {
                return ResourceManager.GetString("Extras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شحن مجاني.
        /// </summary>
        public static string FreeShipping {
            get {
                return ResourceManager.GetString("FreeShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شحن مجاني لجميع الطلبات التي تزيد عن .
        /// </summary>
        public static string FreeshippingonallUSorder {
            get {
                return ResourceManager.GetString("FreeshippingonallUSorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to احصل على تحديثات البريد الإلكتروني حول العروض الخاصة بنا.
        /// </summary>
        public static string GetEmailupdatesaboutourlatestshopandspecialoffers {
            get {
                return ResourceManager.GetString("GetEmailupdatesaboutourlatestshopandspecialoffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملاء راضون.
        /// </summary>
        public static string HappyCustomer {
            get {
                return ResourceManager.GetString("HappyCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرئيسية.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخط الساخن.
        /// </summary>
        public static string Hotline {
            get {
                return ResourceManager.GetString("Hotline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعات العمل.
        /// </summary>
        public static string HoursWorked {
            get {
                return ResourceManager.GetString("HoursWorked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أسرع ! العرض ينتهي في.
        /// </summary>
        public static string HurryupOfferendsin {
            get {
                return ResourceManager.GetString("HurryupOfferendsin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إذا كانت هناك مشاكل في المنتجات.
        /// </summary>
        public static string Ifgoodshaveproblems {
            get {
                return ResourceManager.GetString("Ifgoodshaveproblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انضم لقائمتنا الاخبارية.
        /// </summary>
        public static string JoinOurNewsletterNow {
            get {
                return ResourceManager.GetString("JoinOurNewsletterNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللغة.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل دخول.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارجاع نقدي.
        /// </summary>
        public static string MoneyBack {
            get {
                return ResourceManager.GetString("MoneyBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض المزيد.
        /// </summary>
        public static string MoreCategories {
            get {
                return ResourceManager.GetString("MoreCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحساب.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأخبار.
        /// </summary>
        public static string Newsletter {
            get {
                return ResourceManager.GetString("Newsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string off {
            get {
                return ResourceManager.GetString("off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطلبات السابقة.
        /// </summary>
        public static string OrderHistory {
            get {
                return ResourceManager.GetString("OrderHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فريق العمل.
        /// </summary>
        public static string OurTeam {
            get {
                return ResourceManager.GetString("OurTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دفع آمن.
        /// </summary>
        public static string PaymentSecure {
            get {
                return ResourceManager.GetString("PaymentSecure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جوال رقم.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحقوق والسياسات.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المشارع المنجزة.
        /// </summary>
        public static string ProjectDone {
            get {
                return ResourceManager.GetString("ProjectDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظرة سريعة.
        /// </summary>
        public static string QuickView {
            get {
                return ResourceManager.GetString("QuickView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اقرأ المزيد.
        /// </summary>
        public static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب جديد.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تخفيضات تصل الى.
        /// </summary>
        public static string Saleupto {
            get {
                return ResourceManager.GetString("Saleupto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال.
        /// </summary>
        public static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسوق معنا.
        /// </summary>
        public static string Shop {
            get {
                return ResourceManager.GetString("Shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسوق من:.
        /// </summary>
        public static string ShopBy {
            get {
                return ResourceManager.GetString("ShopBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسوق الان.
        /// </summary>
        public static string ShopNow {
            get {
                return ResourceManager.GetString("ShopNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خريطة الموقع.
        /// </summary>
        public static string SiteMap {
            get {
                return ResourceManager.GetString("SiteMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض خاص لفترة محدودة.
        /// </summary>
        public static string SpecialOfferLimitedTime {
            get {
                return ResourceManager.GetString("SpecialOfferLimitedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تبدأ من .
        /// </summary>
        public static string Startingat {
            get {
                return ResourceManager.GetString("Startingat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to للتجارة !.
        /// </summary>
        public static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموضوع.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إشتراك.
        /// </summary>
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دعم.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أرسل رسالة.
        /// </summary>
        public static string TellUsYourMessage {
            get {
                return ResourceManager.GetString("TellUsYourMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نحن نضمن دفع آمن.
        /// </summary>
        public static string Weensuresecurepayment {
            get {
                return ResourceManager.GetString("Weensuresecurepayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرحبا بك في موقع.
        /// </summary>
        public static string WelcomeTo {
            get {
                return ResourceManager.GetString("WelcomeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة الامنيات.
        /// </summary>
        public static string WishList {
            get {
                return ResourceManager.GetString("WishList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لديك 30 يومًا للاسترجاع.
        /// </summary>
        public static string Youhave30daystoReturn {
            get {
                return ResourceManager.GetString("Youhave30daystoReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ايميلك.
        /// </summary>
        public static string YourEmail {
            get {
                return ResourceManager.GetString("YourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرسالة.
        /// </summary>
        public static string YourMessage {
            get {
                return ResourceManager.GetString("YourMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسمك.
        /// </summary>
        public static string YourName {
            get {
                return ResourceManager.GetString("YourName", resourceCulture);
            }
        }
    }
}
